"""
Hello World API - Generated by AI Development Agent
Task: CMMAI-48 - Setup hello world for agentic workflow implementation
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from datetime import datetime
from typing import Dict, Any
import uvicorn

# Initialize FastAPI app
app = FastAPI(
    title="Hello World API",
    description="A simple Hello World API created by AI Development Agent for CMMAI-48",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)


class HelloResponse(BaseModel):
    """Response model for hello world endpoint"""
    message: str
    timestamp: str
    task_id: str
    generated_by: str


class HealthResponse(BaseModel):
    """Response model for health check"""
    status: str
    service: str
    timestamp: str
    uptime: str


@app.get("/", response_model=HelloResponse)
async def hello_world() -> HelloResponse:
    """
    Hello World endpoint - main functionality for CMMAI-48
    
    Returns:
        HelloResponse: Greeting message with metadata
    """
    return HelloResponse(
        message="Hello, World! This API was created by the AI Development Agent.",
        timestamp=datetime.now().isoformat(),
        task_id="CMMAI-48",
        generated_by="AI Development Agent"
    )


@app.get("/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    """
    Health check endpoint for monitoring
    
    Returns:
        HealthResponse: Service health status
    """
    return HealthResponse(
        status="healthy",
        service="hello-world-api",
        timestamp=datetime.now().isoformat(),
        uptime="running"
    )


@app.get("/api/info")
async def get_api_info() -> Dict[str, Any]:
    """
    Get API information and metadata
    
    Returns:
        Dict: API metadata and task information
    """
    return {
        "api_name": "Hello World API",
        "version": "1.0.0",
        "task_id": "CMMAI-48",
        "description": "Greenfield hello world API for agentic workflow implementation",
        "generated_by": "AI Development Agent",
        "endpoints": [
            {"path": "/", "method": "GET", "description": "Hello world message"},
            {"path": "/health", "method": "GET", "description": "Health check"},
            {"path": "/api/info", "method": "GET", "description": "API information"},
        ],
        "documentation": {
            "swagger_ui": "/docs",
            "redoc": "/redoc"
        }
    }


if __name__ == "__main__":
    print("🚀 Starting Hello World API...")
    print("📋 Task: CMMAI-48")
    print("🤖 Generated by: AI Development Agent")
    print("🔗 Documentation: http://localhost:8000/docs")
    
    uvicorn.run(
        app, 
        host="0.0.0.0", 
        port=8000,
        log_level="info",
        reload=True
    )